package me.rerere.workspace

import java.io.File
import java.net.DatagramPacket
import java.net.DatagramSocket
import java.net.InetAddress
import java.nio.file.Files

class RootfsPatcher {
    fun patch(
        linuxDir: File,
        options: RootfsPatchOptions = RootfsPatchOptions(),
    ) {
        val etcDir = File(linuxDir, "etc")
        if (!etcDir.isDirectory) return

        ensureRootfsDns(etcDir, options)
        ensureHosts(etcDir, options.hostname)
        ensureHostname(etcDir, options.hostname)
        ensureLocale(etcDir, options.locale)
        ensureGroupNames(etcDir, options.groupIds.ifEmpty { currentSupplementaryGroupIds() })
        ensureTempDirs(linuxDir)
    }

    private fun ensureRootfsDns(
        etcDir: File,
        options: RootfsPatchOptions,
    ) {
        val resolvConf = File(etcDir, "resolv.conf")

        // 服务器来源完全由调用方给（app 侧读 setting-json/workspace.json，空则用系统上报）。
        // 这里**不内置任何公共 DNS**：以前写死的 1.1.1.1 排在第一位，而它在国内不响应，
        // 导致每次解析先白等 5s（见 orderByReachability 的注释）。
        val servers = options.nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(MAX_DNS_SERVERS)
            .let { orderByReachability(it) }
        if (servers.isEmpty()) return // 没有任何可信来源：保留现状，别写出一个没 nameserver 的文件

        val content = buildString {
            appendLine("# Generated by RikkaHub workspace.")
            appendLine("# 顺序 = 优先级：glibc 是**串行**试的，不响应的那台要熬满 timeout 才会轮到下一个。")
            servers.forEach { appendLine("nameserver $it") }
            appendLine("options ${options.dnsOptions.ifBlank { DEFAULT_RESOLV_OPTIONS }}")
        }

        val isPlainFile = resolvConf.isFile && !Files.isSymbolicLink(resolvConf.toPath())
        val existing = if (isPlainFile) runCatching { resolvConf.readText() }.getOrNull() else null
        if (existing == content) return

        // 未显式配置时，把一份「里面已经有真实 nameserver」的文件当成别人认真写的，不覆盖。
        // （用户在工作区里自己配过 DNS 就不该被我们推回去。）
        // 显式配置了 workspaceDnsServers 则配置优先，必须重生 —— 否则改设置不生效。
        if (existing != null && !options.forceDnsRewrite) {
            val hasRealNameserver = existing.lineSequence()
                .filter { it.trimStart().startsWith("nameserver ") }
                .any { line ->
                    val server = line.trim().removePrefix("nameserver").trim()
                    server.isNotBlank() && server !in LOCAL_RESOLVERS
                }
            if (hasRealNameserver) return
        }

        if (resolvConf.exists() || Files.isSymbolicLink(resolvConf.toPath())) {
            resolvConf.delete()
        }
        resolvConf.writeText(content)
    }

    /**
     * 把探得到的 DNS 服务器排到前面，探不到的排到后面（保持各自原有顺序）。
     *
     * 为什么必须做：rootfs 里的 glibc 是**串行**试的，而且默认超时 5s。
     * 实测（2026-10-10）设备上报的 DNS 首项是 1.1.1.1，在国内 100% 不响应，
     * 结果**每一次**域名解析都先白等 5s —— 任何联网程序都被拖成「启动即卡 6 秒」。
     * 设备自己的 Android resolver 是并发+自带缓存，所以手机上看不出来，
     * 但进了 rootfs 就原形毕露。
     *
     * 全部探不通（离线/被拦）时**原样保留**：宁可能用的顺序差，也别把 DNS 搞空。
     */
    private fun orderByReachability(servers: List<String>): List<String> {
        if (servers.size <= 1) return servers
        val verdict = java.util.concurrent.ConcurrentHashMap<String, Boolean>()
        // 每个服务器一个短命线程：探测本身是阻塞 I/O，不能赖在调用方线程上
        // （prepareWorkspaceTerminalSession 是在主线程调的，直接 recv 会 NetworkOnMainThread）。
        val threads = servers.map { server ->
            Thread { verdict[server] = probeDns(server) }.apply {
                isDaemon = true
                name = "rikkahub-dns-probe"
                start()
            }
        }
        val deadline = System.currentTimeMillis() + PROBE_BUDGET_MS
        threads.forEach { thread ->
            val left = deadline - System.currentTimeMillis()
            if (left > 0) runCatching { thread.join(left) }
        }
        if (verdict.values.none { it }) return servers
        return servers.sortedByDescending { verdict[it] == true }
    }

    /**
     * 探一个 DNS 服务器活不活：发一个根区 NS 查询，[DNS_PROBE_TIMEOUT_MS] 内有**任何**
     * 回应就算活（REFUSED 也算 —— 我要的是「通不通」，不是「答不答得对」）。
     */
    private fun probeDns(server: String): Boolean = runCatching {
        val address = InetAddress.getByName(server) // 字面量 IP，不会再走 DNS
        DatagramSocket().use { socket ->
            socket.soTimeout = DNS_PROBE_TIMEOUT_MS
            val query = DNS_PROBE_QUERY
            socket.send(DatagramPacket(query, query.size, address, DNS_PORT))
            socket.receive(DatagramPacket(ByteArray(512), 512))
            true
        }
    }.getOrDefault(false)

    private fun ensureHosts(etcDir: File, hostname: String) {
        val hosts = File(etcDir, "hosts")
        val lines = if (hosts.isFile) hosts.readLines() else emptyList()
        val hasIpv4Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "127.0.0.1" && "localhost" in normalized.drop(1)
        }
        val hasIpv6Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "::1" && "localhost" in normalized.drop(1)
        }
        if (hasIpv4Localhost && hasIpv6Localhost) return

        hosts.parentFile?.mkdirs()
        hosts.appendText(
            buildString {
                if (hosts.exists() && hosts.length() > 0 && !hosts.readText().endsWith('\n')) {
                    appendLine()
                }
                if (!hasIpv4Localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") {
                        append(" ")
                        append(hostname)
                    }
                    appendLine()
                }
                if (!hasIpv6Localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            }
        )
    }

    private fun ensureHostname(etcDir: File, hostname: String) {
        val target = File(etcDir, "hostname")
        if (target.isFile && target.readText().trim().isNotBlank()) return
        target.writeText("${hostname.ifBlank { DEFAULT_HOSTNAME }}\n")
    }

    private fun ensureLocale(etcDir: File, locale: String) {
        val defaultDir = File(etcDir, "default").apply { mkdirs() }
        val target = File(defaultDir, "locale")
        val lines = if (target.isFile) target.readLines().toMutableList() else mutableListOf()
        if (lines.any { it.trim().startsWith("LANG=") }) return
        lines += "LANG=$locale"
        target.writeText(lines.joinToString(separator = "\n", postfix = "\n"))
    }

    private fun ensureGroupNames(etcDir: File, groupIds: List<Long>) {
        val target = File(etcDir, "group")
        if (!target.exists()) {
            target.writeText("root:x:0:\n")
        }
        val lines = target.readLines().toMutableList()
        val existingIds = lines.mapNotNull { line ->
            line.split(':').getOrNull(2)?.toLongOrNull()
        }.toSet()
        val existingNames = lines.mapNotNull { line ->
            line.substringBefore(':').takeIf { it.isNotBlank() }
        }.toSet()
        val additions = groupIds
            .filter { it > 0 && it !in existingIds }
            .distinct()
            .map { id ->
                val baseName = "android_gid_$id"
                val name = if (baseName in existingNames) "${baseName}_workspace" else baseName
                "$name:x:$id:"
            }
        if (additions.isEmpty()) return

        target.appendText(
            buildString {
                if (target.length() > 0 && !target.readText().endsWith('\n')) {
                    appendLine()
                }
                additions.forEach { appendLine(it) }
            }
        )
    }

    private fun ensureTempDirs(linuxDir: File) {
        listOf("tmp", "var/tmp", "root").forEach { path ->
            File(linuxDir, path).mkdirs()
        }
        listOf(File(linuxDir, "tmp"), File(linuxDir, "var/tmp")).forEach { dir ->
            dir.setReadable(true, false)
            dir.setWritable(true, false)
            dir.setExecutable(true, false)
        }
        File(linuxDir, "root").apply {
            setReadable(true, true)
            setWritable(true, true)
            setExecutable(true, true)
        }
    }

    private fun currentSupplementaryGroupIds(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(WHITESPACE_REGEX)
            .mapNotNull { it.toLongOrNull() }
    }

    private companion object {
        private const val MAX_DNS_SERVERS = 3

        /** 单个 DNS 探测的等待上限；总预算取它 + 一点余量，因为探测是并行的。 */
        private const val DNS_PROBE_TIMEOUT_MS = 700
        private const val PROBE_BUDGET_MS = 1_200L
        private const val DNS_PORT = 53

        /** 手搓的 DNS 报文：ID=1，RD=1，QDCOUNT=1，QNAME=根，QTYPE=NS，QCLASS=IN。 */
        private val DNS_PROBE_QUERY = byteArrayOf(
            0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01,
        )

        private const val DEFAULT_HOSTNAME = "localhost"
        private val WHITESPACE_REGEX = Regex("\\s+")
        private val LOCAL_RESOLVERS = setOf(
            "127.0.0.1",
            "127.0.0.53",
            "::1",
        )
    }
}

data class RootfsPatchOptions(
    /**
     * rootfs `/etc/resolv.conf` 写哪几台 DNS，**顺序 = 优先级**。
     *
     * 由调用方决定，本模块不内置任何默认值（写死公网 IP 的代价见 [RootfsPatcher] 里 DNS 那段注释）。
     * 空列表 = 没有任何可信来源，此时**不碰** resolv.conf。
     */
    val nameservers: List<String> = emptyList(),
    /** `options` 行内容（不含 `options` 前缀）；空 = [DEFAULT_RESOLV_OPTIONS]。 */
    val dnsOptions: String = "",
    /** true = 忽略现有文件里已有的 nameserver，强制按 [nameservers] 重生（用户显式配置时用）。 */
    val forceDnsRewrite: Boolean = false,
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val groupIds: List<Long> = emptyList(),
)

/**
 * `/etc/resolv.conf` 的 `options` 默认值。
 *
 * - `timeout:1` —— 不响应的服务器最坏只吃 1s，而不是 glibc 默认的 5s。
 * - `attempts:2` —— 别因为一次丢包就放弃这一台。
 *
 * 可以经 `setting-json/workspace.json` 的 `workspaceDnsOptions` 覆盖。
 */
const val DEFAULT_RESOLV_OPTIONS = "timeout:1 attempts:2 edns0 trust-ad"
